### PR TITLE
Fix: CSS for smaller screens and Firefox

### PR DESCRIPTION
**Pull request by atomic-addison**
Using percent units introduces a few issues on smaller screens, especially in Firefox. Consider setting fixed widths or using flexbox if you're not looking to support older browsers.

### CODE REVIEW

**Comment by LeGitHubDeTai** [comment]
sorry i can't merge your PR, because it's no longer compatible with google chrome. please change or create new @media (max-width = XXXXpx) {} in css for add your change

**Comment by atomic-addison** [comment]
> sorry i can't merge your PR, because it's no longer compatible with google chrome. please change or create new @media (max-width = XXXXpx) {} in css for add your change

What's the issue specifically?

**Comment by LeGitHubDeTai** [comment]
Before:
image

After:
image

**Comment by atomic-addison** [comment]
> Before:
> image
> 
> After:
> image

Oh, so you just want me to adjust the icon size? Its not an issue, in fact you could probably set that as a variable. One sec.

**Comment by atomic-addison** [comment]
From what you said I assumed you wanted the icon height to change the bar height as well. I've updated the CSS to do that.

**Review by LeGitHubDeTai — APPROVED** [review]
Thanks for your contribution !

**Pull request merged**
